name: 'DevSecOps to actions-angular'
run-name: 'DevSecOps to actions-angular'

on:
  pull_request:
    types:
      - opened
  workflow_dispatch: 

jobs:
  dev:
    uses: luciopbrito/actions/.github/workflows/angular-dev.yml@feat/angular-dev